<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_obortech_fas fa-angle-down fa-sm</name>
   <tag></tag>
   <elementGuidId>d2671375-8104-49d5-a0a9-adf27e5130ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fas.fa-angle-down.fa-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='userDropdown']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>995720f2-d10b-4e5f-b716-c84dadbe2af0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fas fa-angle-down fa-sm</value>
      <webElementGuid>bf669735-b927-45fb-99bc-76ca378d9607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userDropdown&quot;)/i[@class=&quot;fas fa-angle-down fa-sm&quot;]</value>
      <webElementGuid>67b26682-be79-4067-bc21-1d9d58292127</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='userDropdown']/i</value>
      <webElementGuid>6343b631-c685-4823-8e7c-7ec8441e65b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/i</value>
      <webElementGuid>5cbc2f87-dc14-47c4-9fe2-611213815673</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
