<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Modeller</name>
   <tag></tag>
   <elementGuidId>2ffbfe54-5aee-4fb1-b6ca-a73311220bb3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div/aside/div/div/div/div[2]/div/div/div/div/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d4417450-894d-4e82-97e7-a53dee521166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gap-3 nav-link</value>
      <webElementGuid>335d9adf-d0d1-4461-ae60-e778f9d88fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/asset-modeller/assetmodeller</value>
      <webElementGuid>7d5e6155-3368-4872-8e7b-bd5189a1bff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Modeller</value>
      <webElementGuid>ba95462a-d4ae-4489-91a9-810cee808c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;ltr&quot;]/div[@class=&quot;pageWrapper d-md-block d-lg-flex&quot;]/aside[@class=&quot;sidebarArea&quot;]/div[@class=&quot;sidebarBox shadow bg-white fixedSidebar&quot;]/div[1]/div[@class=&quot;simplebar-wrapper&quot;]/div[@class=&quot;simplebar-mask&quot;]/div[@class=&quot;simplebar-offset&quot;]/div[@class=&quot;simplebar-content-wrapper&quot;]/div[@class=&quot;simplebar-content&quot;]/div[@class=&quot;p-3 pt-3 mt-2&quot;]/ul[@class=&quot;nav flex-column&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;gap-3 nav-link&quot;]</value>
      <webElementGuid>0230c8ff-0dd5-4285-810f-549528396f54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/aside/div/div/div/div[2]/div/div/div/div/ul/li[3]/a</value>
      <webElementGuid>dfed01a3-1bf8-4d12-b097-4f16b30a0621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NFT Digital Certificates'])[1]/following::a[1]</value>
      <webElementGuid>9631bae6-4f9c-4615-b585-d349236c34da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Users'])[1]/following::a[2]</value>
      <webElementGuid>64f2b86d-e51c-4060-a768-8fe64f39fa39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/asset-modeller/assetmodeller')]</value>
      <webElementGuid>ee190bfc-a7eb-47a9-bee1-8fb9c240cfff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>684f0516-34bd-4f84-9822-c20885b36785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/asset-modeller/assetmodeller' and (text() = 'Modeller' or . = 'Modeller')]</value>
      <webElementGuid>cd3d70a1-c2da-4caf-b7bd-eb46467ca967</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
