<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Users</name>
   <tag></tag>
   <elementGuidId>9c85d307-3ced-4e4e-a5f9-d599a18c05ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.gap-3.nav-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/div/div/aside/div/div/div/div[2]/div/div/div/div/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>19669ebc-7a97-4b65-806f-af44ccc4ccd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gap-3 nav-link</value>
      <webElementGuid>700b43c2-4a78-4569-b9e3-4c4bf88c1dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/organization/users</value>
      <webElementGuid>fffb351e-5c0a-43da-b5e0-bf53ab210d8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Users</value>
      <webElementGuid>467dbb52-5165-4648-b3dc-f50105a8739e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;ltr&quot;]/div[@class=&quot;pageWrapper d-md-block d-lg-flex&quot;]/aside[@class=&quot;sidebarArea showSidebar&quot;]/div[@class=&quot;sidebarBox shadow bg-white fixedSidebar&quot;]/div[1]/div[@class=&quot;simplebar-wrapper&quot;]/div[@class=&quot;simplebar-mask&quot;]/div[@class=&quot;simplebar-offset&quot;]/div[@class=&quot;simplebar-content-wrapper&quot;]/div[@class=&quot;simplebar-content&quot;]/div[@class=&quot;p-3 pt-3 mt-2&quot;]/ul[@class=&quot;nav flex-column&quot;]/li[@class=&quot;activeLink nav-item&quot;]/a[@class=&quot;gap-3 nav-link&quot;]</value>
      <webElementGuid>4369c523-fd3a-4e27-9054-1842843327d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/aside/div/div/div/div[2]/div/div/div/div/ul/li/a</value>
      <webElementGuid>9f684388-f3b6-481f-bc6b-12a37efc56d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NFT Digital Certificates'])[1]/preceding::a[1]</value>
      <webElementGuid>9fb55d62-f426-4bee-a4b2-435a1dda5f5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/organization/users')]</value>
      <webElementGuid>ee0c0b98-a0fd-4cbd-907a-09fe9f606c11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>c26088e5-983a-488a-91a8-ddf3991d55a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/organization/users' and (text() = 'Users' or . = 'Users')]</value>
      <webElementGuid>c953feb1-edc5-4143-a57a-8f27f6754936</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
