<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__sidebarOverlay</name>
   <tag></tag>
   <elementGuidId>d071f078-ef00-4a74-8ee0-621ad9af9bbc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.sidebarOverlay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cb4950e2-e55f-4b45-b135-0bef2433f374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sidebarOverlay</value>
      <webElementGuid>a7a4e0c4-75df-4512-986e-d3f542a8beeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[1]/div[@class=&quot;ltr&quot;]/div[@class=&quot;pageWrapper d-md-block d-lg-flex&quot;]/div[@class=&quot;contentArea fixedTopbar&quot;]/div[@class=&quot;p-4&quot;]/div[@class=&quot;sidebarOverlay&quot;]</value>
      <webElementGuid>96d7e2f5-6e41-4713-a02e-20cb68c2ddbe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/div/div/div[2]</value>
      <webElementGuid>3b20f7dc-b4b0-4ce6-a2ca-45c87aae7697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]</value>
      <webElementGuid>7d8c0932-e96e-4f56-918e-3151c9bcaef8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
