<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Text InputDisplay Label16Placeholder La_fe74d9</name>
   <tag></tag>
   <elementGuidId>dfc3d840-4445-49a9-89a3-5db023a089a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-top']/div/div/div/div/div[2]/div/div[2]/div[2]/div/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.edit-form</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b504f492-69ca-41f2-8550-9e341dc10e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>edit-form</value>
      <webElementGuid>65f6b567-b079-4712-9781-095b8eefc1bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Text InputDisplay Label16Placeholder LabelRequiredValidate EmailRegular Expression PatternPrint OptionsPage Break Before Element?Alternate/Signature PageDisplay on alternate/signature Page?Default Selected</value>
      <webElementGuid>3b887b1c-f393-4074-a553-57cfc874f097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-top&quot;)/div[1]/div[@class=&quot;page-top-main-div&quot;]/div[@class=&quot;body-wrapper&quot;]/div[@class=&quot;form-builder-container&quot;]/div[@class=&quot;w-100 overflow-hidden bg-transparent shadow-none card&quot;]/div[@class=&quot;p-4 card-body&quot;]/div[2]/div[@class=&quot;form-builder-middle-box mt-4&quot;]/div[@class=&quot;form-builder-middle-left-box-section mb-3&quot;]/div[1]/div[@class=&quot;react-form-builder clearfix&quot;]/div[@class=&quot;col-md-9 react-form-builder-preview float-left is-editing&quot;]/div[@class=&quot;edit-form&quot;]</value>
      <webElementGuid>7a0ab8a6-3fb3-43af-9a43-22ea35b0a2be</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-top']/div/div/div/div/div[2]/div/div[2]/div[2]/div/div/div/div/div</value>
      <webElementGuid>6bb012c9-15b2-4a25-8fd5-e969e20f0572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::div[6]</value>
      <webElementGuid>fd5427d7-0e41-4dd9-91fb-b375b72df188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::div[6]</value>
      <webElementGuid>5b72aa10-2585-4a86-b8fe-ee87df5bf901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div</value>
      <webElementGuid>397a3a83-7d65-40c1-8da9-56c96808300b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Text InputDisplay Label16Placeholder LabelRequiredValidate EmailRegular Expression PatternPrint OptionsPage Break Before Element?Alternate/Signature PageDisplay on alternate/signature Page?Default Selected' or . = 'Text InputDisplay Label16Placeholder LabelRequiredValidate EmailRegular Expression PatternPrint OptionsPage Break Before Element?Alternate/Signature PageDisplay on alternate/signature Page?Default Selected')]</value>
      <webElementGuid>05b419fe-d8d4-4ee4-bcd2-54c5a5534f14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
