<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__organizationName</name>
   <tag></tag>
   <elementGuidId>aae5df6b-2f23-484b-91c2-0aa8220857dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#organizationName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='organizationName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e09a060-2f43-481d-92f1-f26fa6e97b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>organizationName</value>
      <webElementGuid>49ac1a24-723c-4f06-94ea-dc0b2976326d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>01e71266-9ff0-4306-8bed-98e5774abbbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>organizationName</value>
      <webElementGuid>ceb86ef5-cb16-46ad-b6ce-e6824269bfd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a6852a60-f1bd-40e0-8c9c-3715ee179a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Organization Name</value>
      <webElementGuid>2505597e-7748-45c9-bb2e-0f476f737f97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;organizationName&quot;)</value>
      <webElementGuid>b7d3ba16-701b-45dd-9d79-7b700b4b03f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='organizationName']</value>
      <webElementGuid>0932cb60-841e-4e5d-b3f7-1c8b1686bbb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>e837c95b-db6c-40e4-9665-1db8177bb33e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'organizationName' and @type = 'text' and @id = 'organizationName' and @placeholder = 'Organization Name']</value>
      <webElementGuid>b5dedbda-63b5-4a1e-91ff-10c6c529837c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
