<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Document Categories</name>
   <tag></tag>
   <elementGuidId>31199d85-cddd-4372-bd9c-588bda3046d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#documentCategory</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='documentCategory']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ac7c2eb9-8ba3-4b69-b6ca-1172ad22f546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link </value>
      <webElementGuid>3719ee59-e8b6-423c-ba57-8f0ce5701ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>documentCategory</value>
      <webElementGuid>c265a093-a402-491a-907d-0b455ff3894f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DOCUMENT</value>
      <webElementGuid>d93b13e2-2e3f-4dd6-a852-0f37c86df9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>ce8c7b69-65b0-436d-9860-32663039d59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#documentCategory</value>
      <webElementGuid>8ed8dd1f-c920-4356-a8f7-cbe1b36f86f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>b3e921d8-489e-4938-ad58-bfbac2dce8c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>#documentCategory</value>
      <webElementGuid>2e3c4ac4-ab29-4bee-ab0f-a7b01eced434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5806d410-20d8-43b9-a33b-50941b30b57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Document Categories</value>
      <webElementGuid>c55ce851-7502-4e55-b9ec-7557f849cad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;documentCategory&quot;)</value>
      <webElementGuid>536dabf1-16a1-473c-8df7-540918c338ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='documentCategory']</value>
      <webElementGuid>79f87e86-3633-4490-b1f2-407ce5f9e695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='myTab']/li[3]/a</value>
      <webElementGuid>aa225580-109a-4b54-95e2-551f50b1c363</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Document Categories')]</value>
      <webElementGuid>08cc6d12-1c70-4443-96f5-3a18f8800d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event Categories'])[1]/following::a[1]</value>
      <webElementGuid>75f9ba59-c0eb-4cc5-9907-67c78e022493</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Categories'])[1]/following::a[2]</value>
      <webElementGuid>9ad35ff7-886d-4f81-95d8-dff758dbe9fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Participant Categories'])[1]/preceding::a[1]</value>
      <webElementGuid>b38992ee-37a8-4719-9691-04b265af7442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Station Categories'])[1]/preceding::a[2]</value>
      <webElementGuid>4329a7bb-f113-4a21-9da6-669faca0cd83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Document Categories']/parent::*</value>
      <webElementGuid>f30d60a5-7c1b-421c-936b-94d9f471ffcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#documentCategory')]</value>
      <webElementGuid>fb6363a8-4d14-4291-8ef5-145400b5bffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a</value>
      <webElementGuid>a9a42c05-17a1-4ea2-84cf-153c63809fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'documentCategory' and @name = 'DOCUMENT' and @href = '#documentCategory' and (text() = 'Document Categories' or . = 'Document Categories')]</value>
      <webElementGuid>73b65382-4ab3-440d-8927-207abf81e61e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
