<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Event Categories</name>
   <tag></tag>
   <elementGuidId>6299474b-e40b-4eac-8608-07e93a745e68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#eventCategory</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='eventCategory']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a8f8e545-810f-4794-a911-0dd783e6530e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link </value>
      <webElementGuid>f8925784-798c-4d8d-8253-275fcc5c45a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>eventCategory</value>
      <webElementGuid>1f91144c-6913-438a-b1d1-74e818dc91ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EVENT</value>
      <webElementGuid>33e16abe-070f-4ee7-9d96-1ee5ba3ac8b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>6c3f46c1-7649-454f-a91c-182bd95910a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#eventCategory</value>
      <webElementGuid>583ba26e-6ab8-4da4-a713-39bd6a9fb505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>6301024d-e25f-4af9-99fb-85eb7226eaa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>#eventCategory</value>
      <webElementGuid>6e68f19a-fb45-49e9-8e88-125e9a5f4fb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>34b2ea72-d5c6-4821-a648-1f749a608a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Event Categories</value>
      <webElementGuid>b969d67e-57a9-4e53-88dc-68e4b59f63f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;eventCategory&quot;)</value>
      <webElementGuid>8d1d5ff5-4c25-48d3-a7a2-6b5bd8133f83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='eventCategory']</value>
      <webElementGuid>20932aaa-734e-4c54-989c-7cda89591a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='myTab']/li[2]/a</value>
      <webElementGuid>55dd0cbd-72c0-48bd-9677-4182e801732b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Event Categories')]</value>
      <webElementGuid>1d3e30d5-ecdd-4203-bf84-0c514b2fc0d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Categories'])[1]/following::a[1]</value>
      <webElementGuid>ceb260f6-e6a9-449c-bdda-273414d1d130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notification Settings'])[1]/following::a[3]</value>
      <webElementGuid>5367e0b2-6fed-4581-a775-7247c945849d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Categories'])[1]/preceding::a[1]</value>
      <webElementGuid>d092cfdf-a012-4618-adca-5be3f755fcc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Participant Categories'])[1]/preceding::a[2]</value>
      <webElementGuid>5326321f-7bf1-4216-987b-bccf4dfa22f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Event Categories']/parent::*</value>
      <webElementGuid>7bd7d470-988d-480c-9254-8c87f6f1745f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#eventCategory')]</value>
      <webElementGuid>7380b36d-908c-4fe4-b5d2-6e65361bf1b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[2]/a</value>
      <webElementGuid>2059ff5c-a487-44da-8839-116685518151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'eventCategory' and @name = 'EVENT' and @href = '#eventCategory' and (text() = 'Event Categories' or . = 'Event Categories')]</value>
      <webElementGuid>48964a35-634d-436b-a76d-3007df238458</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
