<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Participant Categories</name>
   <tag></tag>
   <elementGuidId>5075cacf-6676-44e7-beeb-993bfe58755a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#participantCategory</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='participantCategory']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ede94b94-c44f-4c98-a01c-febd969c774f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link </value>
      <webElementGuid>1007bbf8-1ed3-4f02-8e1b-25a943ffc8bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>participantCategory</value>
      <webElementGuid>7d1ed250-f3fd-484c-979c-9c87b51d806f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PARTICIPANT</value>
      <webElementGuid>467e9467-ad1a-40b9-8cd9-913a657f3426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>cccf25ad-22ec-4b7d-84d1-fe207b58b92d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#participantCategory</value>
      <webElementGuid>e6475882-9634-4112-9f70-bdab3a818b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>f2e13d41-90d8-4f40-81f3-539c9311a656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>#participantCategory</value>
      <webElementGuid>de73c857-50da-4b71-9c37-ebb08c41a93f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1f0e7854-a77b-4f09-8f05-e8462af16ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Participant Categories</value>
      <webElementGuid>4de2fc41-62b9-47be-9142-f0f389fe9f23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;participantCategory&quot;)</value>
      <webElementGuid>662d790b-7828-43f8-b04a-354232183235</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='participantCategory']</value>
      <webElementGuid>8bcf1d0f-dc44-4415-a9eb-2b1ef82b1fd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='myTab']/li[4]/a</value>
      <webElementGuid>98e74884-58f0-4ddc-a3f9-2aaeed1a28ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Participant Categories')]</value>
      <webElementGuid>6c8a674b-ec22-4772-82d2-b6b1999ae4ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Categories'])[1]/following::a[1]</value>
      <webElementGuid>501724e4-5619-40d0-8cc4-939d50a605fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Event Categories'])[1]/following::a[2]</value>
      <webElementGuid>c6051209-32ae-473b-9301-5fa7e03ca358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Station Categories'])[1]/preceding::a[1]</value>
      <webElementGuid>4cab53a1-f399-4a60-9167-7142a0ed4dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Categories'])[2]/preceding::a[2]</value>
      <webElementGuid>1d29c174-956b-4d16-a519-7cf66e6a78eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Participant Categories']/parent::*</value>
      <webElementGuid>0b101b52-4d11-4632-9a03-4ffbddb9fb9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#participantCategory')]</value>
      <webElementGuid>2d385d55-875b-4cd6-99e5-0da3fe12eccd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/ul/li[4]/a</value>
      <webElementGuid>864471b5-ad00-4c6e-bda0-9772954f3f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'participantCategory' and @name = 'PARTICIPANT' and @href = '#participantCategory' and (text() = 'Participant Categories' or . = 'Participant Categories')]</value>
      <webElementGuid>1d38f33e-c4c4-47a7-811c-6d5b98f982d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Categories'])[2]/preceding::a[2]</value>
      <webElementGuid>2a209a5d-23c7-4822-a59d-3eb2a800f502</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
