<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Station Categories</name>
   <tag></tag>
   <elementGuidId>3c127601-0c42-4096-b398-19bf9131380b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#stationCategory</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='stationCategory']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>aa3dcfa9-e2f3-4a48-bb21-d073b69d4cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link </value>
      <webElementGuid>072278e7-3b0d-46b6-bd75-4d888ed55286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stationCategory</value>
      <webElementGuid>0af4856e-3311-4f0e-a2dd-c19f37a86819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>STATION</value>
      <webElementGuid>55e923b8-5fa0-445c-9a8d-88ffd7a624b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>e400e818-5485-4187-980c-77ac34590ad2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#stationCategory</value>
      <webElementGuid>8dee29a9-86e9-40e1-a9bc-a78a7f537bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>a632393b-c0b4-4470-b54b-a34a176b144e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>#stationCategory</value>
      <webElementGuid>e60b62cd-63d4-4b86-9a4a-7abb6676cbaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>abfde0cc-1f7d-4428-ae98-d3292bcfffdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Station Categories</value>
      <webElementGuid>eed32fa1-b7da-4d0f-9a63-661b2b037dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stationCategory&quot;)</value>
      <webElementGuid>5d03d47b-1608-4668-b020-4d6b3bde564f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='stationCategory']</value>
      <webElementGuid>19a778d4-fede-48e0-b18f-e7efb9d5ea37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='myTab']/li[5]/a</value>
      <webElementGuid>ee70e9dd-a71a-46c8-a5c6-d0d5a737be26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Station Categories')]</value>
      <webElementGuid>ebd7b19b-9a20-4913-9dc0-979b2d07fde2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Participant Categories'])[1]/following::a[1]</value>
      <webElementGuid>ef4b2a0d-19cb-461a-9435-b71f0f5bfed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Document Categories'])[1]/following::a[2]</value>
      <webElementGuid>09f3357b-148c-48fc-b105-a023f6bbb894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Categories'])[2]/preceding::a[1]</value>
      <webElementGuid>1b48d7aa-70a9-453f-816c-a4664f27ff78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUBMIT CATEGORY'])[1]/preceding::a[1]</value>
      <webElementGuid>dded6e3b-58de-4929-89b6-aa06ba19b8ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Station Categories']/parent::*</value>
      <webElementGuid>3dd727e3-f1f8-4be7-a7a4-f9e731714d6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#stationCategory')]</value>
      <webElementGuid>1d34f465-472e-4c19-b233-a40f1919514f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a</value>
      <webElementGuid>93c670ed-c4ff-4167-9588-7790103c6265</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'stationCategory' and @name = 'STATION' and @href = '#stationCategory' and (text() = 'Station Categories' or . = 'Station Categories')]</value>
      <webElementGuid>d73882e4-1688-4504-a3ed-27ce27460155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Category Listing'])[1]/preceding::a[1]</value>
      <webElementGuid>91772c86-f3f9-423a-bf2d-67292f45e9ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
