<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Radius (In meters)_radius</name>
   <tag></tag>
   <elementGuidId>adba1dfc-465a-4200-ab3b-5313a80a962e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radius</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radius']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fde96c70-47e7-42b6-bd59-2886c85b1739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>a61dee87-1ada-4617-bc42-07e0ccca0256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radius</value>
      <webElementGuid>6a3edd16-8cf0-4b26-a447-a1e74d5325bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7d75afb1-1931-42eb-95cf-44741282308a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radius</value>
      <webElementGuid>a37043bd-cf79-451d-b98f-40147b8dd94c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>default-css form-control</value>
      <webElementGuid>3ab19e7a-8879-4889-b510-9d96dc4fc613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Radius (In meters)</value>
      <webElementGuid>ba3ef9b4-c5eb-404f-a6bc-d20efcdb379e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3b1a9333-b896-45bc-a608-3b4906411f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radius&quot;)</value>
      <webElementGuid>6fa1727d-3a2d-468f-83d9-206f36ac0e84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radius']</value>
      <webElementGuid>a56fc1f2-4679-4325-b135-7119be0cec20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>6333e2ae-26e4-4e27-bd47-f63e9d6b0913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'radius' and @id = 'radius' and @placeholder = 'Radius (In meters)']</value>
      <webElementGuid>1d7eac55-a0e6-4913-b2e6-bf91e5f01256</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
