<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Welcome Back_transactionPassword</name>
   <tag></tag>
   <elementGuidId>a8c31964-feb4-47e6-9d8c-5460bd1edc39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#transaction-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='transaction-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c4471ba-2ca0-4cd8-8750-f6eb38027a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>ae4cb14c-a4fd-4911-830f-db44d7384e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>transactionPassword</value>
      <webElementGuid>1ab52790-6bf6-435a-baf4-f13a78c9d93e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>default-css form-control form-control-user</value>
      <webElementGuid>28b36ff1-1140-4a4c-ab35-95f4dab123c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transaction-password</value>
      <webElementGuid>018a588d-83a3-48fd-be83-2255e0997eb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Blockchain Password</value>
      <webElementGuid>106603a0-0c20-4abb-bf32-8bb87ba150be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transaction-password&quot;)</value>
      <webElementGuid>cda8c411-3d46-4c86-b25d-51a6275dec45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='transaction-password']</value>
      <webElementGuid>030407f7-b98d-46c3-a19a-d2ed677a9382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/div/div/div/div[2]/div/form/div/input</value>
      <webElementGuid>ecc18a1d-e3f9-4b05-b5a9-2ed592b94377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2279dbc6-6df8-4870-a3de-0fb52d9bdd3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'transactionPassword' and @id = 'transaction-password' and @placeholder = 'Blockchain Password']</value>
      <webElementGuid>dfb271cc-c76d-4f2d-885c-339599e2dc57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
