<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Copy</name>
   <tag></tag>
   <elementGuidId>ca0f2dce-fa4d-46e8-af8c-7ebf201212c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='js-btn-copy']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#js-btn-copy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d924f01c-c2b8-4550-83d3-26ad4b8b4c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js-btn-copy</value>
      <webElementGuid>f54f7c67-aa66-4ec3-907d-3e2a1ece066a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>email-block__copy</value>
      <webElementGuid>8b8f2c5b-3225-426d-b3be-1cf998594c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>_temp_mail.copyToClipboard()</value>
      <webElementGuid>78ca5ec8-a56f-4be6-ba75-628425d05e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                            Copy</value>
      <webElementGuid>b5b3941d-8413-4528-a476-be3f464f8a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-btn-copy&quot;)</value>
      <webElementGuid>e44916ea-5a51-48a6-8366-a309c1b2b51e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='js-btn-copy']</value>
      <webElementGuid>52783c16-eed5-4d3d-b42f-d19e5f7b881d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mahesh@gotgel.org'])[1]/following::button[1]</value>
      <webElementGuid>749f0412-5e1c-47e6-9a37-9d726da03c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your temp mail address:'])[1]/following::button[1]</value>
      <webElementGuid>0ee441b3-b908-420d-8444-89f59a258d85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copied'])[1]/preceding::button[2]</value>
      <webElementGuid>438382db-bf04-4a62-b785-db1bd2250def</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Copy']/parent::*</value>
      <webElementGuid>c2f5020d-b194-43fc-87da-8edc294b5827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>bf9893a9-cf4d-4a02-9e25-3fe5b5a0ea67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'js-btn-copy' and (text() = '
                            Copy' or . = '
                            Copy')]</value>
      <webElementGuid>687d7e1e-6bcb-4896-97e9-9f50d8a870cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
