<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Save</name>
   <tag></tag>
   <elementGuidId>c1f1b5ea-02d1-4ecd-90f7-fd8bcef63b65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick='_temp_mail.changeEmail()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.content-edit__saveBtn.btn-change-email-js</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3d0ba083-3089-4df7-a9e2-9bc9dbab1b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content-edit__saveBtn btn-change-email-js</value>
      <webElementGuid>7e9dbbcc-46f0-49c5-bcf9-44394d7b71d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>_temp_mail.changeEmail()</value>
      <webElementGuid>7e26a1eb-9eb9-4db6-b9b1-6db5c3e2e7b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>39f6e02d-6488-48f1-924a-29ea9a10e711</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_tm_changeEmail&quot;)/div[@class=&quot;mailBox-block__content content-edit&quot;]/div[@class=&quot;content-edit__saveBtn btn-change-email-js&quot;]</value>
      <webElementGuid>42c2424e-29e5-427f-b253-10fa1873eba0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick='_temp_mail.changeEmail()']</value>
      <webElementGuid>0e1d592d-eca9-40e1-9c3d-dc7ff874a08f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_tm_changeEmail']/div[2]/div[3]</value>
      <webElementGuid>54cbfb86-e6c9-4be2-a239-e963c1b50999</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@jollyfree.com'])[1]/following::div[1]</value>
      <webElementGuid>5189c3ad-0220-42e6-b955-3ebc6906d6fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@rungel.net'])[1]/following::div[2]</value>
      <webElementGuid>f2edbbff-be6c-4f64-b7fb-ef76ed4d5a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='THE BEST TEMP EMAIL INBOX'])[1]/preceding::div[1]</value>
      <webElementGuid>2f3ae75a-f653-48b2-b856-2b0286d9cb02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='THE BEST TEMP EMAIL INBOX'])[2]/preceding::div[1]</value>
      <webElementGuid>c3e4ba85-ba54-4b4c-882d-9eaacab11c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>9d94b48f-421b-43e2-8092-549366148677</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div[3]</value>
      <webElementGuid>18c7f88c-fb55-4879-af18-a1a2152b4faa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>9cf29eda-8e38-4ce0-af2a-aea6452a4acd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
