<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Back_content-edit__login new-email-ad_32f1b6</name>
   <tag></tag>
   <elementGuidId>39eccadd-2960-4afa-9218-f0048b52c42e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.content-edit__login.new-email-address-js</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4326baac-d5eb-4400-8b00-fb20794dde95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content-edit__login new-email-address-js</value>
      <webElementGuid>6acafa6f-3dc6-4fd3-8f14-3f172ff2b965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>11521281-c3c0-4d84-95d8-70d9c64a45cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>da52a12a-00cd-47b3-b413-38015b6485f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_tm_changeEmail&quot;)/div[@class=&quot;mailBox-block__content content-edit&quot;]/div[@class=&quot;content-edit__cover&quot;]/input[@class=&quot;content-edit__login new-email-address-js&quot;]</value>
      <webElementGuid>a320ffd2-6ed8-450f-9285-05e3f414cca9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>347342c9-9213-444b-89d7-74d092f87aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_tm_changeEmail']/div[2]/div[2]/input</value>
      <webElementGuid>3b5946d2-9169-4df3-871d-0df806e18100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9c32b64e-10f6-495b-99fe-430c5b337900</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'login']</value>
      <webElementGuid>4403ba07-3a66-4463-9b8c-713fd6d92d97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
