<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Welcome Back_transactionPassword</name>
   <tag></tag>
   <elementGuidId>27632d07-1ac0-48c9-a54f-e9659604747e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#transaction-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='transaction-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf68ebff-5a40-411c-8c2b-04d0d334c6e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>a83ce8c7-cf47-4ac1-b81a-3bbecdb2c46f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>transactionPassword</value>
      <webElementGuid>ebf3af65-90ec-49e2-9f2c-68c8f7c07ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>default-css form-control form-control-user</value>
      <webElementGuid>aa48f4d8-0148-49c4-897b-e93bac92ca7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transaction-password</value>
      <webElementGuid>6757ae72-a823-477f-9b39-baf47b7334f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Blockchain Password</value>
      <webElementGuid>3e2fd850-d496-4ec2-ae4d-d03ca33c94b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transaction-password&quot;)</value>
      <webElementGuid>d54a8373-ded1-400a-8ade-2c50f87aaa07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='transaction-password']</value>
      <webElementGuid>6265e25e-e49c-45fd-b605-d96953a192ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/div/div/div/div[2]/div/form/div/input</value>
      <webElementGuid>9a02a765-6bbc-4ced-b9a5-b24d2c5db3bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>503d5f02-bf31-448f-a8c8-ce75cb19cd89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'transactionPassword' and @id = 'transaction-password' and @placeholder = 'Blockchain Password']</value>
      <webElementGuid>312b1b87-475f-4bc0-911c-763e8badf97f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
