<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Project creation live_projectsearch-input</name>
   <tag></tag>
   <elementGuidId>a806be38-f6e4-40cc-8c09-fa1a438add6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.projectsearch-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='c']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cbae3f3b-f319-41f4-9b4a-d868bb85dbb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>projectsearch-input</value>
      <webElementGuid>2760296b-78a2-45a7-b828-d0d3e3165788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>1f822cd7-6d6d-4619-a429-1fd4fd6df002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search projects...</value>
      <webElementGuid>6ce2741b-a782-4467-9d39-da2ee1a8c978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>c</value>
      <webElementGuid>f92bab2a-6bc0-4944-91eb-4ec2c97d6741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordionSidebar&quot;)/li[1]/form[@class=&quot;d-none d-sm-inline-block form-inline navbar-search&quot;]/div[1]/div[@class=&quot;projectsearch&quot;]/input[@class=&quot;projectsearch-input&quot;]</value>
      <webElementGuid>adf384cd-141e-4b33-bbff-fe06f515c3d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='c']</value>
      <webElementGuid>cc932113-d08e-4b41-bb04-c4e5132aaace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='accordionSidebar']/li/form/div/div/input</value>
      <webElementGuid>b01480e0-866f-4c4e-8115-4d9641517c13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>2720d37a-c3f7-409e-ab77-f1bb785609b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @placeholder = 'Search projects...']</value>
      <webElementGuid>20e74d2d-864b-492b-8362-24d20d917957</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='C']</value>
      <webElementGuid>e26c535d-5b89-4968-ad9d-0c89701d4af5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
