<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Transporter  Jason</name>
   <tag></tag>
   <elementGuidId>870749fc-7fe9-4b6c-91a2-fd56c774d583</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#collapsed1392</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='collapsed1392']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>17e2f33b-9352-419f-ae9c-64927d12bbad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>collapsed1392</value>
      <webElementGuid>04bd6787-f99a-41a5-97a4-7fcc28fdcb5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link collapsed</value>
      <webElementGuid>20e1d30b-408e-4a24-800c-b67040bb9f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>4ffa74a5-5d23-4987-9c22-c64e9ae3900a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#collapse1392</value>
      <webElementGuid>0574afb7-93a0-4c51-85d3-224eec2496b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8e4aecfd-38ff-4967-980f-5cdbb75a6958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>collapse1392</value>
      <webElementGuid>6189f75f-7d6a-4684-a844-825926a349fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Transporter | Jason</value>
      <webElementGuid>a03959a3-e566-4fe5-a41d-98e7282299a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collapsed1392&quot;)</value>
      <webElementGuid>1b6f1d36-177e-4174-b81e-b1a24fa0fae7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='collapsed1392']</value>
      <webElementGuid>0c11bd2a-a20f-4a2c-8cd4-24a0079c24b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='1413']/div/span</value>
      <webElementGuid>7dbbac43-cda1-4c36-b2ab-e19588c96668</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Watch all'])[1]/following::span[1]</value>
      <webElementGuid>aa07a636-4173-4f73-8de0-9396e21428ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Choco chip Project'])[1]/preceding::span[2]</value>
      <webElementGuid>aac56059-b925-4725-842f-b7d63206a2f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/span</value>
      <webElementGuid>9de58482-a64b-48c7-8fbf-024f6ef0c3f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'collapsed1392' and (text() = 'Transporter | Jason' or . = 'Transporter | Jason')]</value>
      <webElementGuid>b477163a-bbc9-48cc-883e-dfe057f4c901</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
