<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Welcome Back_transactionPassword</name>
   <tag></tag>
   <elementGuidId>2f36e656-6619-4586-9f51-279cfe5152b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#transaction-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='transaction-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c70b0c1-b923-403c-839d-b5d70d8f451d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>8b7ade4a-23eb-4047-a397-ce4f7425d3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>transactionPassword</value>
      <webElementGuid>f9574990-3c5c-4539-b743-e28bb337c994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>default-css form-control form-control-user</value>
      <webElementGuid>af3294ec-9d9a-4721-8c19-488cf38b9a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transaction-password</value>
      <webElementGuid>645d5d02-f84b-42b7-998b-aef7b7a77f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Blockchain Password</value>
      <webElementGuid>f252d2bc-f48d-4f59-af28-19aeb5b8bd38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transaction-password&quot;)</value>
      <webElementGuid>9db65f58-4da0-419c-b5da-4ce8ffd7079b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='transaction-password']</value>
      <webElementGuid>bb0912d9-aa18-4088-87f2-4e66e9a3f2ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div/div/div/div/div[2]/div/form/div/input</value>
      <webElementGuid>543fc9b1-ee90-495f-be13-7533060cf71e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b2c4b756-84c8-470c-96f5-2e0aaac59439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @name = 'transactionPassword' and @id = 'transaction-password' and @placeholder = 'Blockchain Password']</value>
      <webElementGuid>d2a6beb6-9665-4b4d-bf5a-8b6afa086e87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
